### ISSUE TITLE
Code, pre, and kbd styles

### ISSUE THREAD

**Issue by kognise** [kognise/water.css#1]
We need styles for inline code, inline keyboard shortcuts, and code blocks. This includes the following tags:

- `<code>`
- `<kbd>`
- `<pre>`

Possibly also the following:

- `<samp>`
- `<output>`

Any help would be appreciated!

**Comment by DanielBiegler** [comment]
Oh neat, been also interested in this kind of bare bones CSS so I guess I might just now contribute.

Lemme check it out. :)

**Comment by DanielBiegler** [comment]
How about something like this? The "this" is a `<kbd>`, btw.

![image](https://user-images.githubusercontent.com/14810858/55656954-14443b80-57f9-11e9-80e8-9d340de092cc.png)

**Comment by kognise** [comment]
Looks great! How is the orange color-contrast wise?
