### ISSUE TITLE
Prevent scroll bar from causing a layout shift

### ISSUE THREAD

**Issue by ubershmekel** [kognise/water.css#100]
Because the layout is centered - a scroll bar coming in and out causes a slight shift. This is mostly visible in single page apps where the header should be static but it clicks to the side when moving between long and short pages.

`min-height: 101%` causes the scroll bar to always show up which is what this kind of layout needs.

**Comment by jonaskuske** [comment]
If you use
```
html {
  overflow: scroll;
}
```
you achieve the same result (scrollbar always visible), but without that little 1% scroll no matter how tall the site actually is.

Still, I'm not sure how I feel about this – it seems like a very hacky workaround to a minor problem and shouldn't be done through water.css itself but in userland imo, so users can decide for themselves if they want it or if they want to use another approach.
[On this site](https://jonaskuske.github.io/ng-app) for example, I used [the `calc(100vw - 100%)` trick](https://css-tricks.com/elegant-fix-jumping-scrollbar-issue/) to prevent content shift without having the scrollbar always be visible.

**Comment by kylejrp** [comment]
I think that adding `overflow-y: scroll` is a fairly safe option.

I don't think targeting SPAs is in line with the goals of the project, but fixing weird problems like a scrollbar popping in/out would be in scope.

The only downside is this would be adding a scrollbar to pages that don't need it - for example, tiny demo sites that don't have enough content to fill the screen.

I'd love to hear more feedback from the community on if this would positively or negatively impact your project.

**Comment by jthegedus** [comment]
I've been using this for an SPA and enjoy the experience, whilst my SPA has a lot of content and requires scrolling and doesn't affect me, I would like to voice people are using it for SPAs.

**Comment by morgs32** [comment]
Can you make it optional? The scrollbar is the one thing I would leave alone. Surprised this was worth the code?

**Comment by morgs32** [comment]
You cannot even unset these properties: https://stackoverflow.com/questions/9060421/css3-how-to-restore-webkit-scrollbar-property-to-the-default-scroll-bar

**Comment by kognise** [comment]
This is the main reason I've opted to not include any sort of styling like this in Water.css - sorry for the lack of communication on this. It's a very easy change to make if you need to make it and I don't believe warrants being added to the base stylesheet, especially because for non-scrolling pages a persistent scrollbar might be considered ugly.

**Comment by morgs32** [comment]
Styling like what? Are you proposing a PR to remove the scrollbar code?

**Comment by kognise** [comment]
Oh, I see, you're talking about something completely different from the original issue. I don't currently have any plans to change the scrollbar.

**Comment by morgs32** [comment]
Aww you know how sensitive engineers get when you tell them their comments are erroneous or irrelevant. Which is to say, should I have opened an issue "Scroll bar is causing layout shift... and not styling it is how I suggest we resolve it". 

That aside, I'm quite grateful for the work you're doing. I'm sure this is all a nuisance.

**Comment by kognise** [comment]
Oh not a nuisance at all! I'm doing my unfortunate thing where I'm busy with tons of things and haven't given enough time to this. Just got a bit confused.

I'm gonna close this issue but if anyone wants to start a separate discussion about scrollbars feel free to make a new issue.
