### ISSUE TITLE
Dev server not working

### ISSUE THREAD

**Issue by kognise** [kognise/water.css#101]
The development server doesn't live reload on changes and doesn't automatically build on CSS changes.

**Comment by jonaskuske** [comment]
I can look into this bug this weekend, if I can reproduce it :)

**Comment by seriouslysean** [comment]
I was able to reproduce this issue @kognise and @kylejrp -- added a PR to address the bug here, https://github.com/kognise/water.css/pull/140. Let me know if you need anything else!

**Comment by kognise** [comment]
This has also been fixed
