### ISSUE TITLE
Multiple select has arrow in the middle

### ISSUE THREAD

**Issue by mohd-akram** [kognise/water.css#104]
Add `multiple` to the select tag in the demo page to see. Perhaps it would be helpful to have a multiple select element in the demo page also.

**Comment by kylejrp** [comment]
Great suggestion. We'd take a pull request for this!

**Comment by olgark** [comment]
I would like to work on this issue, unless you were planning on it, @mohd-akram. Please let me know!

**Comment by mohd-akram** [comment]
Sure, go ahead :D

**Comment by kylejrp** [comment]
I think that #107 already beat you too it. Sorry @olgark!

**Comment by olgark** [comment]
@kylejrp @mohd-akram It looks like the PR did not actually solve this issue. Is it bad etiquette for me to create a PR that removes the arrow and styles the multiple select as the issue stated, or should I wait for the PR creator to fix it? Hacktoberfest is brutal 😅

**Comment by kylejrp** [comment]
Ah, I misunderstood! #107 doesn't fix this bug. Oops.

#107 added the issue to the demo page. We'd still be looking for the issue to be resolved. 

@olgark What pull request are you referring to? Can you link to it here? If it's stale, you're welcome to pick it up and work on it where they left off.

**Comment by olgark** [comment]
@kylejrp it’s the one you referenced above. If you look at the discussion, it seems it was intended to solve the issue, and the creator of the PR is going to fix it.

**Comment by kylejrp** [comment]
I'm not seeing that discussion on that pull request. It looks like #107 was only intended to update the demo page. The only other users in that thread are myself and @mohd-akram, and we're both okay with you taking the issue on.

It's yours if you want it @olgark! 😁

Let me know if you'd like any help or if you have a WIP pull request you'd like me to review.

**Comment by olgark** [comment]
@kylejrp oh! My mistake. The conversation was between you and mohd-akram. I thought it was between the PR author and mohd-akram. In that case, yes I’ll do it! Sorry for the confusion.

**Comment by olgark** [comment]
@kylejrp I have created a pull request (see above). Thanks!
