### ISSUE TITLE
Can we have an option to remove max-width from body?

### ISSUE THREAD

**Issue by khuongduybui** [kognise/water.css#105]
I love everything about this framework except for the fact that it forces max-width on my body.
I am proud to wear my body fat.

**Comment by kylejrp** [comment]
We try to avoid configuration where possible. We're having to do it in 2.0.0 for browser compatibility, but I'm not sure that we're ready to do it for cosmetic items like this.

I don't want to `<body>`-shame though. For your use case, is this something you'd be able to override with your own custom stylesheet after water.css? For example:
```
html {
    max-width: initial;
}
```

**Comment by khuongduybui** [comment]
That's what I currently resort to. Thanks.
