### ISSUE TITLE
Remove `dist` folder

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#109]
The `dist` folder should be removed in favor of publishing these build artifacts through npm. We would want to remove these files, add `dist` to `.gitignore` and create a new `.npmignore` that excludes the same files as `.gitignore` except for the `dist` folder.

This will make pull requests easier to review and prevent contributors from having to build beforehand.

This is probably a breaking change and should be done with the release of 2.0.0.

**Comment by melanieseltzer** [comment]
Is this something I could work on? I'd like to contribute :)

**Comment by kylejrp** [comment]
It's all yours @melankeseltszer! Let me know if you need any help.
