### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#110]
A guide for contributors needs to be created. This should move the contributing content from [`README.md`](https://github.com/kognise/water.css/tree/f0709f5517a671faf5007c60a335cca89869cf1f#contributing) into `.github\CONTRIBUTING.md` and update it for the changes from #71. 

In scope for this issue:
- Prerequisites to install (yarn, what commands to run)
- How to find issues to work on (good-first-issue/help-wanted tags)
- Folder structure description
- How to make a pull request (small scope, good description/commits)
- Link to community conduct

Out of scope for this issue:
- Any changes to code files
- Any reorganization of the repository to make contributing easier
- Any future changes from open pull requests that haven't been merged yet (no NPM documentation yet)

**Comment by justinasposiunas** [comment]
I would like to take this one :)

**Comment by kylejrp** [comment]
It's yours @justinasposiunas! Let me know if you have any questions or want me to review a WIP pull request.

**Comment by kylejrp** [comment]
Closed by #120
