### ISSUE TITLE
Seperate browserlist for modern builds

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#111]
`gulpfile.js` has multiple builds - one for legacy browsers that don't support CSS variables, and one for modern browsers that do.

We could use two browserlists to help reduce filesizes:
- Our current browserlist could become the legacy browserlist
- A second browserlist that only includes browsers with CSS variables compatibility 

To work on this issue, you would need to:
- Get a list of browsers that support CSS variables. [caniuse](https://caniuse.com/#feat=css-variables) would be a good resource.
- Create a new modern browserlist in `gulpfile.js`. 
- Use the new browserlist in the modern build section by modifying the call to `autoprefixer()` https://github.com/kognise/water.css/blob/f0709f5517a671faf5007c60a335cca89869cf1f/gulpfile.js#L82-L83

**Comment by JanSchneider1** [comment]
Hi, I would like to work on this issue :)
