### ISSUE TITLE
Inconsistent coding style - Semicolons in .js

### ISSUE THREAD

**Issue by JanSchneider1** [kognise/water.css#114]
Currently some .js files have a different coding style regarding semicolons `;`
The `index.js` and `gulpfile.js` don't use `;` after statements, but the `script.js` does.

In my opinion even when `;` are not needed, they can help improve readability and can prevent
mistakes.

**Discussion**: What coding style should we use?

**What changes do you want to be made?**: Perform a refactor for all .js files to apply the choosen coding convention.

**Comment by jonaskuske** [comment]
This is directly related to https://github.com/kognise/water.css/issues/73

If we have a prettier setup (or similar) the style will be kept consistent without further effort. Right now we don't have any linting or formatting config at all, so everyone's editor uses whatever they have defined as their global default config. In my case that means no semicolons, so the files I touched where formatted according to that the moment I saved.

The question about which formatting style we prefer was asked in #73 as well, so we might want to merge these two issues. :)
My personal preference and thus my default is no semi (as you can see from some of the files in the repo), but I'm perfectly fine with either and I agree that semicolons might be more beginner-friendly!

**Comment by kognise** [comment]
Thanks for the feedback! Closing this in favor of #73.
