### ISSUE TITLE
Add blockquotes

### ISSUE THREAD

**Issue by kognise** [kognise/water.css#13]
Blockquote styles are probably the next step! These would probably involve a thick left border of sorts which might need it's own Sass variable.

And let's think about whether or not a footer inside a blockquote should be styled differently for citing a source.

If you decide to take this upon yourself, thanks!

**Comment by FedeAPerez** [comment]
I'd love to participate in this PR, would you mind if I help somehow?

**Comment by kognise** [comment]
@FedeAPerez What do you think needs improvement?

Maybe refactor it to not use the `$focus` variable? Maybe a `$blockquote` variable could exist. The readme would also have to be updated
