### ISSUE TITLE
Support <dialog>

### ISSUE THREAD

**Issue by khuongduybui** [kognise/water.css#139]
Here's what I currently have (trying to mimic details / summary as much as possible).

```
dialog {
  background-color: var(--background-alt);
  color: var(--text-main);

  border: none;
  border-radius: 6px;
  border-color: var(--border);

  padding: 10px 30px;
}

dialog > header {
  background-color: var(--background);

  border-radius: 6px 6px 0 0;

  margin: -10px -30px 10px;
  padding: 10px;

  text-align: center;
}
```

**Comment by kylejrp** [comment]
This looks like a good element to support!

@khuongduybui would you be able to put together a pull request and reference this issue? A pull request would create a Netlify preview that would make it easier to review.

Thanks for your contribution!
