### ISSUE TITLE
Add Style Linting to CI pipeline

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#142]
One of the recommendations from #115 was:
> Potentially adding style linting to a CI pipeline

**Comment by kognise** [comment]
Imo a pre-commit hook to run `yarn lint` is fine for now, but I'm happy to leave this conversation open to a second opinion.

**Comment by kylejrp** [comment]
I think the pre-commit hook is fine. Would a GitHub action to lint before merging give us more benefit? Like is there a way that an unlimited change could sneak in?

**Comment by kognise** [comment]
I think for now it's fine, but if we end up making an action to automatically publish the package based on changesets we should make sure to lint just in case.

Gonna close this for now.

**Comment by kylejrp** [comment]
Sounds good. I'm going to close #143 as well since this discussion also applies there.
