### ISSUE TITLE
Add HTML validation

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#146]
We're not checking the validity of HTML for the demo page. This was noticed in #119.

It would be nice to have something added to check for HTML validity - either something that lints the HTML files, or something that makes the build task fail when HTML isn't valid.

I would be looking for recommendations on how to do this and would be open to any pull request that accomplishes the goal!

**Comment by m-a-y-a-n-k** [comment]
Hi , I am willing to work on this issue but I need some guidance

**Comment by pchessah** [comment]
I would like to work on this

**Comment by kognise** [comment]
In 2.0 we're linting JavaScript inside HTML but not checking the HTML for validity. I'm gonna keep this open, but it isn't important enough to be part of 2.0.

**Comment by aastha0507** [comment]
Can I fix this issue?

**Comment by kylejrp** [comment]
Closing since 2.0 has a `validation` script that handles this now.
