### ISSUE TITLE
Contribution Guide Additions

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#147]
Add information to `.github/CONTRIBUTING.md` regarding:
- Linting (#115)
- Not adding any classes or ids to CSS files
- Theme color guidelines:
  - Reuse existing colors where possible and only for the purpose that their variable describes (eg. don't use text variables for background colorss)
  - Add new colors to both theme files if necessary
  - Don't add colors directly to the css files
  - How to create your own custom theme file (like #42 had done for a "community" theme)

A pull request could be made for each individual item!

**Comment by 108thavenue** [comment]
Hi @kylejrp, I can work on this issue.

Could you please tell me more about what to document regarding linting? I read over the previous discussions and see that only basic linting has been merged in so far. It seems like it will be a one-liner saying something like "our linter is configered to use [JavaScript Standard Style](https://standardjs.com/)", unless I'm missing something. Any guidance would be appreciated.

I'll create separate PRs for the second and third bullet points.

**Comment by 108thavenue** [comment]
Also @kylejrp, could you please elaborate on what you mean by "don't add colors directly to the CSS files"? How else should contributors add colors? Thank you.

**Comment by burhan786** [comment]
hi,can i work on this issue

**Comment by jonaskuske** [comment]
> How to create your own custom theme file

@kylejrp What exactly do you mean by this? Isn't that covered by the theming section in the Readme?

**Comment by kognise** [comment]
Correct me if I'm wrong but I think this issue is from before that was added to the readme?

**Comment by jonaskuske** [comment]
fixed in 2.0 (#194)
