### ISSUE TITLE
Pixels or relative units?

### ISSUE THREAD

**Issue by luminarious** [kognise/water.css#168]
Current best practice is still to use rem for specifying sizes: https://www.24a11y.com/2019/pixels-vs-relative-units-in-css-why-its-still-a-big-deal/

**Comment by kognise** [comment]
Font sizes are currently specified with `em` and margin/padding are specified with `px` as is best practice. Do you think `rem` would be better over `em`?

**Comment by luminarious** [comment]
Like the article elaborates, they look identical when using browser default settings. The difference is what happens when the user has impaired vision and changes the default font-size and/or sets a minimum font size. Rem-based layouts are more flexible and will still look on-brand, even if not identical to design, whereas pixel-based layouts can outright break.

**Comment by kognise** [comment]
As I said, the font sizes are all styled in ems and the spacing is in pixels. This doesn't break the layout at all and this is how I develop all my websites. This has never been a problem, and it's also what a lot of other web developers do.

Here's a screenshot of what Water.css looks like with zoomed in text:

![Screenshot with zoomed in text](https://please.dont-hack.me/1rkqqscua9n79.png)

What we might want to look at is the misplacement of the check box and radio button indicators when at larger font sizes, so those could do with a refactoring.

Thanks!

**Comment by luminarious** [comment]
Alright, glad I could help 🙂
