### ISSUE TITLE
Position of dot in selected radios

### ISSUE THREAD

**Issue by david-donachie** [kognise/water.css#169]
Selected radio buttons use a :before with a bullet character (•), however this doesn't display centred on Windows 10 Firefox. The bullet is lower than the midline of the control.

A substitute is to use a circular box with a space as the generated content. The following seemed to work for me, though the dots are larger than before

content: ' '
background: var(--form-text);
width: 0.4em;
height: 0.4em;
border-radius: 50%;

**Comment by MuhammadUmer0** [comment]
Hi, I have solved the issue (positions of radio buttons) and also created PR for it. Kindly review it thanks

**Comment by acerspyro** [comment]
![image](https://user-images.githubusercontent.com/4400999/79915829-b4b1d180-83f5-11ea-8907-a2c8fbdeacb2.png)

**Comment by kognise** [comment]
In 2.0 we reverted to stock radio buttons and checkboxes, so I'm gonna close this for now.
