### ISSUE TITLE
Navigation / breadcrumbs example / support

### ISSUE THREAD

**Issue by kaihendry** [kognise/water.css#175]
Any hints how to do this?

Using https://getbootstrap.com/docs/4.0/components/breadcrumb/ as a starting point:
```
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Library</a></li>
    <li class="breadcrumb-item active" aria-current="page">Data</li>
  </ol>
</nav>
```

Appears as:

![image](https://user-images.githubusercontent.com/765871/76602263-84992800-6545-11ea-9a70-5e273405533e.png)

So obviously could be improved.

Many thanks!

**Comment by avanigup** [comment]
what imrpovement is needed?

**Comment by kylejrp** [comment]
I imagine that they are looking for something like Bootstrap does for breadcrumbs:
![image](https://user-images.githubusercontent.com/6742479/86043789-08482900-b9fe-11ea-8bba-ba9eb87eb039.png)

The challenge we face here is that water.css doesn't support adding any classes to your markup, so we would need to find a semantic way to structure the breadcrumbs. CSS Tricks offers an article about this called [Exploring Markup for Breadcrumbs](https://css-tricks.com/markup-for-breadcrumbs/). There was a proposal to add semantic breadcrumbs to HTML5 using `rel="up"`, but the article above shows that that proposal is now dead.

We could add naively add selectors for `nav > ol` and `nav > ol > li`, but this may style other non-breadcrumb elements.

I think for now we just need a proposal of the type of semantic HTML we could support in water.css, keeping in mind that we can't depend on any classes or IDs.

**Comment by kaihendry** [comment]
Actually I got what I want via nav https://github.com/kaihendry/blog/commit/02edfa2c280ad47e7d9ec1345d3aa8ef7376d181
