### ISSUE TITLE
input color style

### ISSUE THREAD

**Issue by juancarlospaco** [kognise/water.css#178]
`<input type="color">` Style are weird, mostly on non-chromium based engines,
on Firefox and others the color line is ~2px really hard to see the chosen color,
go to [live demo](https://watercss.netlify.com) and change some input to `type="color"` with inspector and you can Repro the Bug.
I am developing a [Water-based Desktop GUI framework](https://juancarlospaco.github.io/webgui/#buitminusin-dark-mode) and it displays weird too.

**Comment by kognise** [comment]
Fixed by #222
