### ISSUE TITLE
Buttons have same BG color as table stripes

### ISSUE THREAD

**Issue by ethanpil** [kognise/water.css#181]
When using a button inside a table cell the `--background` color variable is used for both and you cannot see the button on alternating rows.

Some ideas to address this:

- Swap default background for buttons to use `--background-alt` and then `--background` on hover
- add a border on buttons
- add a new color for buttons and hover

 Happy to submit a PR if you agree this is an issue and have a preference on how to address it.

![image](https://user-images.githubusercontent.com/254784/80928779-8e782400-8d5b-11ea-818a-6d8cfcde223a.png)

**Comment by Shankhanil** [comment]
I would like to take a look.

**Comment by ruchikamuddinagiri** [comment]
Hi, I would like to work on this. Could you guide me as to where I might find this in the codebase?

**Comment by ruchikamuddinagiri** [comment]
I am not able to replicate this issue.
Attaching the screenshot below:
![image](https://user-images.githubusercontent.com/52284361/91589547-82058000-e977-11ea-9094-e2140172b112.png)

**Comment by kodebae** [comment]
Has this issue been fixed yet? I would like to take a look at this for you.
