### ISSUE TITLE
Printing with Dark Theme should use Light Theme instead

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#188]
When printing with `dark.css`, most browsers will swap out the dark background for a light one, but the heading fonts will still remain a faded light color.

`dark.css` should have it's media query for the light variables changed to:
```
@media (prefers-color-scheme: light), print {
    ...
    (light variables here)
    ...
}
```

A similar line should be added to the `light.css` so that users with `prefers-color-scheme: dark` don't end up using the dark theme for printing too.

I'll wait until we're further along with the `two` branch before making a pull request.

**Comment by kognise** [comment]
This has been fixed by #192 :^)
