### ISSUE TITLE
Tidying Up

### ISSUE THREAD

**Issue by kognise** [kognise/water.css#189]
While preparing for the release of 2.0 I noticed that a lot of our code is inconsistent, and a lot of the JavaScript is pretty hard to read.

I'm going to work on fixing up the JS, but we'll also have to update the CONTRIBUTING.md with the new directory structure with the `docs` folder.

It would also be nice to standardize versions and commit messages, @jonaskuske mentioned some things [in this comment](https://github.com/kognise/water.css/issues/187#issuecomment-634379748). Atlassian's Changesets looks like a really strong option.

Is there anything else we have to clean up?

**Comment by kylejrp** [comment]
If we don't already have it configured, we should have a linter like Prettier that enforces code style.

**Comment by jonaskuske** [comment]
The builds `light-legacy.css` and `dark-legacy.css` in `src/builds/` currently reference `jsdelivr@latest` – they should probably use relative URLs if that's possible?

**Comment by kimulaco** [comment]
I've previously created a PullRequest that adds an EditorConfig.
I think this also helps keep the code consistent.

Issue: https://github.com/kognise/water.css/issues/144
PR: https://github.com/kognise/water.css/pull/152

**Comment by kylejrp** [comment]
Making sure that the GitHub pages site redirects to the current version of the demo / version picker would also be important. See https://github.com/kognise/water.css/pull/158 for a `<meta>` redirect example.

**Comment by kognise** [comment]
In commit 332e8ce I set eslint and stylelint up, added an editorconfig, and cleaner up some of the code a small amount.

> Making sure that the GitHub pages site redirects to the current version of the demo / version picker would also be important. See #158 for a <meta> redirect example.

Absolutely.

**Comment by kognise** [comment]
I just initilalized Changesets and added it to our CONTRIBUTING.md along with info about linting. Now I'll work on adding the Changesets bot and setting up a CI workflow for publishing. I might also publish the current version of Water.css to NPM.

**Comment by kylejrp** [comment]
The current version in master has breaking changes already, so make sure you publish it as a 2.0.0 to follow semantic versioning.

**Comment by kognise** [comment]
Gonna close this because we now have linting, husky, an editorconfig, and updated the file structure. 🚀
