### ISSUE TITLE
Review updated Chrome form controls for impact

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#190]
Chrome is updating their form UI:
https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html

We may want to review to see if this breaks anything in water.css. We may need to reset some of the styling that Chrome is trying to do.

**Comment by jonaskuske** [comment]
I'm using the new Edge (based on Chromium) and had to add `line-height: 0` and `transform: translateX(-50%)` to `input::before`, otherwise the checkbox was off. Here, for reference: https://codepen.io/21stCenturyJonas/pen/QWjpxwG

**Comment by kognise** [comment]
The codepen isn't working for me but I'll install edge and do some testing.

**Comment by jonaskuske** [comment]
Oh, interesting... Are you using Safari?
Works in Chrome, Edge (old & new), Firefox and Opera for me

**Comment by kognise** [comment]
I'm using Brave.

**Comment by jonaskuske** [comment]
Hmm, Brave does not allow CodePens to use `localStorage` :/
Fixed, it renders now

**Comment by kognise** [comment]
I fiddled around a bit with styles, this is the best I could get it across browsers.

Chrome Canary:  
![](https://doggo.ninja/WOwGAN.png)

Edge:  
![](https://doggo.ninja/li1no1.png)

Brave:  
![](https://doggo.ninja/JU1xNl.png)

Safari:  
![](https://doggo.ninja/EgE2lz.png)

Keep in mind I was only able to test on macOS so it might be screwed up on other platforms.

**Comment by jonaskuske** [comment]
I can check and add screenshots for pre-Chromium Edge and IE11 tomorrow :)
Also, these are just radio buttons – how are checkboxes doing?

**Comment by kognise** [comment]
Thanks! Checkboxes look exactly the same.

**Comment by jonaskuske** [comment]
Edge Legacy:
![image](https://user-images.githubusercontent.com/30421456/83296824-b3907300-a1f1-11ea-9d44-893cdb1a15b7.png)

Internet Explorer:
![image](https://user-images.githubusercontent.com/30421456/83296866-c7d47000-a1f1-11ea-84e0-23f459ce88b7.png)

(JS doesn't load though...)
