### ISSUE TITLE
Add emoji fonts to font stack

### ISSUE THREAD

**Issue by jonaskuske** [kognise/water.css#193]
Need to create a repro, but I added this utility to the docs site stylesheet for a reason:

![image](https://user-images.githubusercontent.com/30421456/83318168-7d271800-a232-11ea-9bbc-cd80ee4320ea.png)

Without allowing the browser to fall back to the system's emoji font, some glyphs don't render at all or use some weird tiny black-and-white fallback. (and even when adding those fonts, a few emoji just don't work in browsers on Android even though they work elsewhere in the OS... But there's no way around that 🙄)

So we should really add them to the default font config of water.css, without that (some) emoji are broken. The emoji fonts can come last in the font-family list afaik.

**Comment by jonaskuske** [comment]
Hah, a possible repro was *right there*, if only I had scrolled on the docs page earlier...
![image](https://user-images.githubusercontent.com/30421456/83318574-59fe6780-a236-11ea-8baa-4c4ccc049b55.png)

when adding `, 'Segoe UI Emoji', 'Apple Color Emoji', 'Noto Color Emoji'` to the end of the stack:

![image](https://user-images.githubusercontent.com/30421456/83318591-7f8b7100-a236-11ea-93ae-91dfe387945e.png)

**Comment by kognise** [comment]
Fixed in 7a656de78e74fabb0b38f8ae1628fcc1cec30b16 :rocket:
