### ISSUE TITLE
CDN css files aren't full

### ISSUE THREAD

**Issue by DmitryOlkhovoi** [kognise/water.css#195]
This CSS file didn't have all styles
https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.min.css

**Comment by kylejrp** [comment]
Hey Dimitri,

We're just working on a new release of water.css that should have all the styles you're looking for. Keep your eyes on #194 for the details! We'll also be publishing to npm once we release the new version too.

Sorry that you ran into this problem!

**Comment by DmitryOlkhovoi** [comment]
Thanks!
