### ISSUE TITLE
Water.CSS breaks text align for inputs.

### ISSUE THREAD

**Issue by isuckatprogram** [kognise/water.css#214]
In my CSS file, I have a file called ``style.css`` and on the style, body is assigned to ``text-align: center`` but when I put water.css into my website it breaks the text align for inputs and they are not aligned but everything else is.

**Comment by kognise** [comment]
This is because inputs are `display: block` - it might help to make the body a flexbox container and align everything center. I'm gonna close this because it isn't really an issue but feel free to ask questions in this thread.
