### ISSUE TITLE
Radio buttons

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#22]
Radio buttons don't appear correctly and seem unselectable:
![image](https://user-images.githubusercontent.com/6742479/55691682-8336a700-5955-11e9-9973-838e85492071.png)

Due to these lines:
https://github.com/kognise/water.css/blob/2b4962fc1351aef59d7d7a163c0806a4224a9bc6/src/parts/_forms.scss#L28-L30

**Comment by kognise** [comment]
Good catch! I'll figure out the best course of action that'll result in the smallest file size.

**Comment by Olliebaba** [comment]
```
input:not([type$='x']), input:not([type$='o']), select, button, textarea {
  -webkit-appearance: none;
}
```
🙃

**Comment by kognise** [comment]
@Olliebaba Sorry for my ignorance... what is the `$='x'` syntax?

**Comment by kognise** [comment]
I made some changes! Mind checking out this PR? Thanks. #39
