### ISSUE TITLE
Missing sourcemaps in npm distribution

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#227]
Looks like the sourcemaps may be missing from the `/out/` folder in the npm distribution. Here's what it looks like in my `/node_modules/` folder:
![image](https://user-images.githubusercontent.com/6742479/95421351-27563100-08f2-11eb-9bd9-15d633d92d31.png)

This also seems to break sourcemaps for jsdelivr:
https://cdn.jsdelivr.net/npm/water.css@2/out/water.min.css.map

**Comment by jonaskuske** [comment]
Hmm yep, seems like we're explicitly only publishing CSS files and the license, not the entire `out/` directory.
https://github.com/kognise/water.css/blob/master/package.json#L77

Should be an easy fix :)

**Comment by kognise** [comment]
Great catch! I think I'll just include this in my post-2.0 changes pr.

**Comment by kognise** [comment]
#247 solves this the opposite way, by removing sourcemaps in the built files altogether. This is definitely something that can be discussed separately but for now consistency is preferred I think.
