### ISSUE TITLE
Dialog is not working in Firefox

### ISSUE THREAD

**Issue by ipelekhan** [kognise/water.css#231]
Hi, seems like `Show me the dialog` button is not working in Firefox. Tried the latest version without any extensions. Chrome works fine.

**Comment by kylejrp** [comment]
Yes, the `<dialog>` element is not supported in Firefox without enabling a flag. Looks like it's also unsupported in Safari:
https://caniuse.com/dialog

If this is affecting a project you're using Water.css with, you could look at including a polyfill for the `<dialog>` element, like https://github.com/GoogleChrome/dialog-polyfill

Browsers not having support for elements that we style is out of scope for Water.css to fix. I think the Water.css documentation could be clearer on this, so I'll open up a separate issue to improve our documentation.
