### ISSUE TITLE
Add documentation for elements Water.css supports that some browsers don't

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#233]
See #231 for context

We should include in either the example page or our readme that we style some elements like `<dialog>` that are not supported by other browsers. You can check [caniuse](https://caniuse.com/dialog) for browser support for HTML elements.

We would take a pull request that would add this to the documentation. Ideally, you would check all the HTML elements in the example page and see what elements we style that are unsupported by major browsers. I suspect that it's just `<dialog>`, but it would be nice to confirm.

**Comment by PawanKolhe** [comment]
I can work on this. Please assign it to me.

**Comment by Pedroemanuelavelar** [comment]
Hello done check out the pull request! Please return feedback

**Comment by Pedroemanuelavelar** [comment]
Add this issue for me i already finished it

**Comment by PeeyushRawat** [comment]
Assign this to me! also please guide me.

**Comment by chacha-chaudhary** [comment]
Would Like to work on this

**Comment by kognise** [comment]
I gotta double check the existing PR, I'll ping you if this still isn't solved.

**Comment by Pedroemanuelavelar** [comment]
okay!

Em qua., 25 de ago. de 2021 às 10:16, Kognise ***@***.***>
escreveu:

**Comment by ajaykrupalk** [comment]
I actually worked on this and is pull request 259 titled Documentation

**Comment by wangtianxing1010** [comment]
Hi, I am a new github user and trying to help here, but how would I be able to view the code or branch for this issue if anyone has been working on it?

**Comment by kognise** [comment]
Caniuse links+warnings added to the documentation.
