### ISSUE TITLE
Firefox looks weird vs Chrome

### ISSUE THREAD

**Issue by hovancik** [kognise/water.css#236]
Hi there,

wanted to update to v2 when I noticed the demo looks a bit off on Firefox for me

Left is Chromium, right is Firefox 83 (Debian Sid)

![image](https://user-images.githubusercontent.com/4745859/99804924-06613c80-2b3c-11eb-8928-f13088c3e289.png)

**Comment by jonaskuske** [comment]
Hmm, very strange indeed!
Can't reproduce this myself unfortunately, don't have a Debian Sid machine to test 😕
(but looks fine for me in Firefox Windows, macOS and Ubuntu 20.04 & Debian Buster via WSL + VcXsrv)

**Comment by hovancik** [comment]
Yeah, actually looks normal in Ubuntu for me as well. Probably then problem with Firefox build in Sid.
