### ISSUE TITLE
Input type="reset" lacks button styling

### ISSUE THREAD

**Issue by Ascor8522** [kognise/water.css#239]
Hi,
Noticed the `input` tag, when having the `type` attribute set as `reset` (when resetting a `form` for example) doesn't have the same behavior as the other buttons.

## Actual Behavior
The input:
- [x] has a darker background color, like a button
- [x] has rounded corners, like a button

## Expected behavior
The input should:
- [ ] get brighter when hover by the mouse cursor
- [ ] turn the cursor into a "pointer" cursor when hovered
- [ ] have that animation of moving down and growing when clicked

**Comment by itsdeekay** [comment]
Hi @kylejrp / @

Please assign this to me. I am new to open source community and I have just created a pull request for this issue.

**Comment by itsdeekay** [comment]
Hi @jonaskuske 
I have submitted the pull request. Please review and let's close this issue.

**Comment by jonaskuske** [comment]
@itsdeekay 
Merged, thanks for the contribution! (:

**Comment by jonaskuske** [comment]
Pinging @kognise as he'll have to publish the new version
(we don't have an automatic Git/CI based publish workflow yet and he's the only one with publishing rights for the npm package)

**Comment by itsdeekay** [comment]
Cool, thanks!
