### ISSUE TITLE
::-webkit-details-marker pseudo element selector is deprecated

### ISSUE THREAD

**Issue by mic-max** [kognise/water.css#245]
I see this error in the console on Edge and Chrome 90.
[Deprecation] . Please use ::marker instead. See [https://chromestatus.com/feature/6730096436051968](https://chromestatus.com/feature/6730096436051968) for more details.

Changes to be made:

- `src/parts/_misc.css` - Replace `summary::-webkit-details-marker` with `summary::marker`
- `src/parts/_print.css` - Delete `summary::-webkit-details-marker`

I could provide an accompanying PR as well, the above changes appear to work with Chrome and Edge. I am not sure about other browsers using webkit.

**Comment by jonaskuske** [comment]
I think for now we'll want to keep both selectors around for browser support – though autoprefixer might just do that for us automatically, even if we only keep `::marker` in the codebase
