### ISSUE TITLE
font-family is weirdly specific leading to bad spacing

### ISSUE THREAD

**Issue by ccxvii** [kognise/water.css#248]
The font-family list in the stylesheet is both too long and weirdly specific, yet incomplete. I don't have any of these very specific Windows, Apple, or Android fonts installed on my machine, so it picks the first one it can find which is "Noto Color Emoji" and uses that as the main font. The end result that all the space characters are about two miles wide, and the rest is rendered using the browser default "sans-serif".

You list 13 different sans-serif fonts, and two emoji fonts. The browser is perfectly capable of picking its own Emoji font for emoji characters so this is all completely unnecessary.

Please just use "font-family: sans-serif". There's no need for this level of complicated font family micro-management that doesn't even work.

If you really must have the Emoji fonts, put them _after_ the generic family (sans-serif) in the list, so they only get picked for characters not present in the browser's default sans-serif font.

**Comment by kognise** [comment]
The long font list is there for a reason - many default browser `sans-serif` fonts are unattractive so it provides a list of sensible defaults. However, when making this I did just take one already being used online and didn't fully consider what would happen if none of the standard fonts were available. 

I'll probably just take your advice on this:

> If you really must have the Emoji fonts, put them after the generic family (sans-serif) in the list, so they only get picked for characters not present in the browser's default sans-serif font.

**Comment by easrng** [comment]
Just use `-apple-system, system-ui, sans-serif`, it uses the system font on all recent browser and falls back to sans-serif when the system font isn't available. (Old browsers, mostly.) Including the emoji fonts is not necessary because the emojis "fall through" to the system emoji font anyway.

**Comment by soham283** [comment]
I would like to work on this issue, can you please assign me this issue?

**Comment by omnaladkar** [comment]
i want to work on this can you assign me

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, Can I get started with this?

**Comment by swarup4741** [comment]
> The font-family list in the stylesheet is both too long and weirdly specific, yet incomplete. I don't have any of these very specific Windows, Apple, or Android fonts installed on my machine, so it picks the first one it can find which is "Noto Color Emoji" and uses that as the main font. The end result that all the space characters are about two miles wide, and the rest is rendered using the browser default "sans-serif".
> 
> You list 13 different sans-serif fonts, and two emoji fonts. The browser is perfectly capable of picking its own Emoji font for emoji characters so this is all completely unnecessary.
> 
> Please just use "font-family: sans-serif". There's no need for this level of complicated font family micro-management that doesn't even work.
> 
> If you really must have the Emoji fonts, put them _after_ the generic family (sans-serif) in the list, so they only get picked for characters not present in the browser's default sans-serif font.

Link your own font of choice (may be google fonts or your own custom fonts) using link tag before you link your stylesheet

**Comment by kognise** [comment]
#252 won't load for me for some reason :/
