### ISSUE TITLE
Issue with "Noto Color Emoji" on Firefox / Linux

### ISSUE THREAD

**Issue by scottjmaddox** [kognise/water.css#249]
A reader of a blog post I wrote [complained about a styling issue](https://lobste.rs/s/rqc2sj/introducing_dawn_part_1#c_p1tzb9) with `water.css`. His comment includes a link to an image. It appears to be an issue on Linux Firefox.

It [sounds like](https://lobste.rs/s/rqc2sj/introducing_dawn_part_1#c_nlurzw) removing that font from the CSS fixes the issue. I'm not sure what the other consequences of doing so would be, though.

**Comment by kognise** [comment]
Closing because duplicate of #248 - I'll try to fix ASAP, sorry!
