### ISSUE TITLE
Theme toggle support for bookmarklet 

### ISSUE THREAD

**Issue by HarshitJoshi9152** [kognise/water.css#256]
I just recently tried the bookmarklet and its felt awesome !
is there any way we can add some way to enable theme toggling when using the bookmarklet on other websites ?
Sorry if this already exists, couldnt find it.

**Comment by kognise** [comment]
That's a good idea! I'd been hoping for something like that myself - maybe we can inject some sort of button into the page?

**Comment by HarshitJoshi9152** [comment]
ya i was thinking about the same thing !
is it okay if i work on this ?

**Comment by kognise** [comment]
Absolutely! The bookmarklet source code is in `bookmarklet/original.js` and we've been using [this generator](https://mrcoles.com/bookmarklet/) I believe.

**Comment by HarshitJoshi9152** [comment]
yup found that, thanks for the lightning fast response :+1:
