### ISSUE TITLE
The color of selected text

### ISSUE THREAD

**Issue by roj1512** [kognise/water.css#262]
The color of selected text should have a different variable rather than `--text-bright`.

In my case I want to do this:

In dark mode: background `#222`, text `#eee`, selected text background `#eee`, selected text color `#222.`
In light mode: background `#eee`, text `#222`, selected text background `#222`, selected text color `#eee`.

But `--text-bright` makes a conflict which leads some tags like `h1` totally invisible.

While this can be fixed with a little custom code, it would be cooler if it is fixed water.css side.

**Comment by whizzbbig** [comment]
I can look into this issue like I can able to integrate sass techniques

**Comment by rojserbest** [comment]
@rajputarjun2001 I can't assign people to this.

**Comment by kognise** [comment]
@rajputarjun2001 I'll assign you, lmk if you're not interested anymore

**Comment by kognise** [comment]
I added `--selection-foreground` in the development branch, the naming may change before the big release but I believe this is what was suggested.

**Comment by rojvv** [comment]
Thanks!
