### ISSUE TITLE
Highlight forms inputs in red when they're invalid (eg. blank required field)

### ISSUE THREAD

**Issue by adamerose** [kognise/water.css#276]
I think this would be a great addition. It would require a new CSS color variable like `--danger`, and would target the selector `:invalid:not(form)`

`holiday.css` does this, here's an example: https://holidaycss.js.org/kitchen-sink/#form

![image](https://user-images.githubusercontent.com/10884874/147161327-1c5beeaa-4240-4cc2-92da-8f43db1157bb.png)

Let me know if this change would be acceptable and I could submit a PR.

**Comment by shagungarg0** [comment]
can i work on this issue??

**Comment by kognise** [comment]
I was experimenting with this. I'm not sure it's a great idea - it leads many form fields to be red before the user has even touched them, which often isn't desired behavior and is bad for UX imo. What are your thoughts?

**Comment by adamerose** [comment]
> I was experimenting with this. I'm not sure it's a great idea - it leads many form fields to be red before the user has even touched them, which often isn't desired behavior and is bad for UX imo. What are your thoughts?

On second thought I completely agree with you. It seemed like a neat addition when I saw it but I do think inputs should only appear red after interaction or submission... which would probably require JS and doesn't seem within the scope of water.css. Maybe if css eventually supports a selector indicating whether an input has been touched or modified, then this could be revisited.
