### ISSUE TITLE
adding some creative background to https://watercss.kognise.dev/

### ISSUE THREAD

**Issue by shagungarg0** [kognise/water.css#279]
can i add some background to the site..as it would look interesting after that??

**Comment by ashutoshdhande** [comment]
Can you please describe what is required just a responsive background with slight effects or some animations?

**Comment by ghost** [comment]
The site is meant to be a demo page

**Comment by kognise** [comment]
Yeah, I'm not a sure a creative background is a great idea. I do want to redesign a large portion of Water.css though and release a major v3.
