### ISSUE TITLE
Support for <details>, <summary>

### ISSUE THREAD

**Issue by rahuldottech** [kognise/water.css#30]
```
<details>
<summary>Sample Text</summary>
<p>Read this sample text.</p>
</details>
```
This is some neat HTML code which allows for collapsible/toggle-able content, but it'd be neat if the content within `<p>...</p>` was in a dotted border or something to make it easily distinguishable from the previously already displayed stuff.

**Comment by kylejrp** [comment]
MDN has good documentation on the [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) and [`<summary>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary) elements.

They offer good suggestions for [customizing the disclosure widget](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Customizing_the_disclosure_widget).

It mentions having to use a vendor prefixer `::-webkit-details-marker` for styling in Chrome, but hopefully the autoprefixer will catch that.

**Comment by kylejrp** [comment]
We'd love to have someone contribute to this issue!

To contribute, we'd be looking for you to add a new `.scss` file in `/src/parts/`. You'll want to reuse any variables from `src/dark.scss` or `src/light.scss` if they make sense, or create and reference new variables if necessary.

There's lots of creative freedom with this issue. Feel free to try something unique, as long as it fits in with the general aesthetic of water.css!

Let us know if you need any help or if you have any questions about how to contribute!

**Comment by Showtim3** [comment]
@kylejrp @rahuldottech Hey I'd like to help with this..

**Comment by kylejrp** [comment]
It's yours, @Showtim3! 

The current master branch has been reorganized a little bit from my previous explanation above. If you have any trouble finding out where the new files are, let me know.

Feel free to respond here or open up a WIP merge request when you've made some progress!

**Comment by Showtim3** [comment]
@kylejrp i probably have to write a ```css``` file instead of ```scss``` right? and I am going through the suggestions from the previous PR, that's fine right?
