### ISSUE TITLE
Arrange <li> items in a <nav> horizontally

### ISSUE THREAD

**Issue by adamerose** [kognise/water.css#325]
Could `water.css` lay out `<li>` elements horizontally when they're inside a `<nav>`? Other classless CSS libraries do this like holiday.css, awsm.css, tacit, writ, and MVP.css

I think holiday.css is the best example [[1](https://compare-classless-css.netlify.app/?style=holiday.css), [2](https://master--60d4b39b36bc1d003b029b44.chromatic.com/?path=/story/content-sectioning-nav--with-ul), [3](https://github.com/EvgenyOrekhov/holiday.css/blob/master/src/css/nav.css)]

@kognise if you're okay with the idea let me know and I'll contribute a PR for it.

---

`holiday.css` 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/10884874/218657279-f542de12-c854-4514-8187-6aa738520587.png">

`water.css`
<img width="617" alt="image" src="https://user-images.githubusercontent.com/10884874/218657260-3e3da5ea-e162-4618-b653-3b4330a6e150.png">

**Comment by Ritika8081** [comment]
can I work on this project

**Comment by adamerose** [comment]
Actually I just noticed I think this is a duplicate of https://github.com/kognise/water.css/issues/182 where there's already some discussion
