### ISSUE TITLE
Profile section 

### ISSUE THREAD

**Issue by harshsingh32** [kognise/water.css#330]
Profile section is missing in the website, it should be provided.

**Comment by Vishal-Parasram** [comment]
@harshsingh32 assign me incan work in this issue

**Comment by prologic** [comment]
What does profile section mean here?

**Comment by sachin3825** [comment]
Hello @harshsingh32 I would like to contribute to this project I am proficient in React.js , CSS frameworks and JavaScript I want start my journey in open source contribution

**Comment by heimoshuiyu** [comment]
Why is everyone asking "assign this to me" but I have never seen a commit? This is an open source project, you submit a pull request and wait for it to be merged, or you maintain your own fork.

**Comment by RupeshBhalekar** [comment]
what is menay by profile section here?
means exactly what to do in profile section
