### ISSUE TITLE
Issues being spammed with "Assign this to me" comments?

### ISSUE THREAD

**Issue by adamerose** [kognise/water.css#348]
I noticed a weird trend on this project where every issue has people spamming comments asking to be "assigned" to work on them. My guess is there is some bootcamp sending students to work on open source for grade credit or something...

https://www.github.com/kognise/water.css/issues/332
https://www.github.com/kognise/water.css/issues/278#issuecomment-1718812017
https://www.github.com/kognise/water.css/issues/299#issuecomment-1272341209
https://www.github.com/kognise/water.css/issues/299#issuecomment-1427726131
https://www.github.com/kognise/water.css/issues/338#issuecomment-1671036025
https://www.github.com/kognise/water.css/issues/338#issuecomment-1677703146
https://www.github.com/kognise/water.css/issues/338#issuecomment-1692786861
https://www.github.com/kognise/water.css/issues/338#issuecomment-1712576558
https://www.github.com/kognise/water.css/issues/330#issuecomment-1493823524
https://www.github.com/kognise/water.css/issues/330#issuecomment-1494682502
https://www.github.com/kognise/water.css/issues/327#issuecomment-1474219967
https://www.github.com/kognise/water.css/issues/326#issuecomment-1718807145
https://www.github.com/kognise/water.css/issues/320#issuecomment-1319571253
https://www.github.com/kognise/water.css/issues/320#issuecomment-1502929054
https://www.github.com/kognise/water.css/issues/320#issuecomment-1533019847
https://www.github.com/kognise/water.css/issues/309#issuecomment-1279316367

**Comment by kylejrp** [comment]
This is probably on me, I added water.css to some "good first issue" repo a long time ago, but we're probably no longer a good fit

**Comment by elidakirigo** [comment]
> This is probably on me, I added water.css to some "good first issue" repo a long time ago, but we're probably no longer a good fit

I was about to be one of the spammers, to be honest until I came across this issue, I found this repo on hacktoberfest [hacktoberfest](https://hacktoberfest-projects.vercel.app/repos/css) and would like to ask if you'll be accepting any pull request this year?

**Comment by adamerose** [comment]
To be clear I was mostly referring to the "assign this to me" terminology. Usually the `Assignees` GitHub tag is used for employees or members of a project who own a particular feature. If you're making a contribution as an outsider usually you just do it and submit a PR. I've never seen a single person ask to be "assigned" to an issue on on open source GitHub project before, let alone [12 in a row](https://github.com/kognise/water.css/issues/303) without anyone actually working on it.

I wouldn't refer to new contributors or hacktoberfest in general as spam, just found those comments weird and unique to this repo.

> would like to ask if you'll be accepting any pull request this year?

I'm not affiliated with the project but my guess would be no since the last commit date is 2 years ago, this repository looks unmaintained.

**Comment by elidakirigo** [comment]
> To be clear I was mostly referring to the "assign this to me" terminology. Usually the `Assignees` GitHub tag is used for employees or members of a project who own a particular feature. If you're making a contribution as an outsider usually you just do it and submit a PR. I've never seen a single person ask to be "assigned" to an issue on on open source GitHub project before, let alone [12 in a row](https://github.com/kognise/water.css/issues/303) without anyone actually working on it.
> 
> I wouldn't refer to new contributors or hacktoberfest in general as spam, just found those comments weird and unique to this repo.
> 
> > would like to ask if you'll be accepting any pull request this year?
> 
> I'm not affiliated with the project but my guess would be no since the last commit date is 2 years ago, this repository looks unmaintained.

thanks for the clarification.
