### ISSUE TITLE
Filesize Goal Conflicts

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#36]
Hey @kognise! I just wanted to open up a friendly discussion on the filesize goal. I think it's holding water.css from being the best it can be.

One of the water.css goals is:

> - Small size (< 2kb)

However, it's come up that adding some new features would increase the file size:
https://github.com/kognise/water.css/issues/32#issuecomment-481253756
https://github.com/kognise/water.css/issues/22#issuecomment-480650691
https://github.com/kognise/water.css/pull/14#issuecomment-480850907
https://github.com/kognise/water.css/pull/19#issuecomment-480679096

I think this conflicts with some of the other goals:
> - Good code quality

Having a file size constraint encourages writing less-legible but smaller sized CSS rules.

> - Good browser support

Autoprefixing is taking up some of the file size.

> - Beautiful

A small file size is preventing new features from being added.

---
Proposition:
- Remove the specific file size from the goal, but still keep the goal about a small file size.
- Advertise the gzip'd file size from the CDN somewhere on the demo page. (It looks like jsdeliver serves dark.css in 856 B, which is much smaller than the 2 KB! Maybe gulp could calculate this at build time? Or javascript could calculate the real response size on the demo page?)

This would allow water.css to encourage readable code, add support for any browser, and add any kind of features. I think keeping a small file size as a goal will still discourage adding things like background images to the .css file and bloating it.

**Comment by kognise** [comment]
Totally agreed! This is one of the reasons I haven't been moving on with some of the PRs and issues - I was considering what to do size constraint-wise.

I agree that this is a good proposition. One last thing, though - do you think < 3kb is realistic or should we just drop the entire size constraint like you recommended?

If we go for < 3kb in the future it might get bigger and we don't want to seem like we keep expanding it.

**Comment by kognise** [comment]
test

**Comment by kognise** [comment]
Mentioning a CDN... multiple people on HN though a CDN for Water.css would be cool. Although that's probably not a good idea right now, it could be a thing to consider in the future and could automate part of the development workflow.

**Comment by kylejrp** [comment]
What's the motivation behind having a specific file size listed?

If its performance, the CDN takes 10x as long to start serving a file compared to the time it takes to download the file. (I think it was something like 300ms time to first byte vs 10ms download)

**Comment by kylejrp** [comment]
(talking about the current CDN, jsdelivr)

**Comment by kylejrp** [comment]
Agreed! I did some research on what the community considers to be small.

Here's the sizes after being gzip'd for a bunch of other frameworks that are specifically trying to be small file size ([source](https://www.webfx.com/blog/web-design/small-css-frameworks/)):
![image](https://user-images.githubusercontent.com/6742479/56006167-abd9dc00-5c88-11e9-9650-5d2a298e643d.png)

I think even if we picked something like 10KB before being gzip'd, we'd still be considered a small/lightweight framework. But again - I don't think we should limit ourselves by picking a specific file size.

I unscientifically compared Bootstrap 4 from both Bootstrap's CDN, jsdelivr to what we currently serve with Water.css on jsdelivr:

|                    | Bootstrap's CDN | Boostrap jsdelivr | water.css jsdelivr |
| ------------------ | ----------------- | ------------------- | -------------------- |
| Waiting (TTFB)   | 32.41ms         | 29.69ms           | 30.98ms            |
| Content Download | 6.51ms          | 3.23ms            | 1.15ms             |
| Total            | 38.92ms         | 32.92ms           | 32.13ms            |

Bootstrap is 20KB minified, so we're not going to see a huge loss of performance as we increase the filesize.

**Comment by kognise** [comment]
@kylejrp Thank you! It's interesting that Bootstrap's CDN is slower than Jsdelivr. Also, I didn't realize Milligram was that big! On their website they advertise "Only 2kb gzipped!", so are you sure that's accurate?

**Comment by kylejrp** [comment]
You're right - I just tested it and for `milligram.min.css` I got:
`Original size: 8930 bytes Result size: 2278 bytes`

Since I had the gzip calculator open, `water.css` gets:
`Original size: 2549 bytes Result size: 1042 bytes`

I think we're in the clear for a while, especially since compression is on our side as we continue to repeat ourselves in our CSS. 😎

For reference, Milligram's site takes 46ms for it to download the minified and gzipped CSS as well on my connection.

**Comment by kognise** [comment]
Ok, I'm finally taking a look at this now.

**Comment by kognise** [comment]
@kylejrp Okay, I started a PR with some changes in #63
