### ISSUE TITLE
Move to Netlify?

### ISSUE THREAD

**Issue by kognise** [kognise/water.css#40]
I'm considering switching to [Netlify](https://www.netlify.com/) for our website. Here are some benefits of doing this:

- Faster deployments of updates to the demo site
- Ultra fast loading (does this matter that much?)
- And, the most important thing at least to me: **deployments of the demo for every pull request**

This way anyone can view someone's new styles without downloading or installing anything. The main con of switching is that Netlify is a separate addon and might complicate things for a project in an early-ish stage.

I'd love to hear the community's feedback on this - what are your thoughts?

**Comment by kylejrp** [comment]
I love it! I'm a big fan of Netlify, let me know if you need a hand with this.

I don't think Netlify will complicate the project too much - it's just sitting "on top" of the project. The deploys would be handled invisibly to users, and we could even integrate the preview links into pull requests.

**Comment by joshkmartinez** [comment]
I think netlify is great!
I don't think it will complicate the project too much. The preview links I think would be a resource to have (especially since this project is a CSS framework)

**Comment by kognise** [comment]
Ok, I set up the initial Netlify things. [This](https://watercss.netlify.com/) is where the site will now be deployed. Things to still do:

- Update links in readme, etc.
- Setup PR deployments

**Comment by kognise** [comment]
Actually, everything should be set up! Lemmme make a test PR.

**Comment by kylejrp** [comment]
Awesome work! 🎉

**Comment by kylejrp** [comment]
Should we keep the GitHub Pages deployment up still? I think that's what was linked to from the reddit/HN post, so if we do remove it, we should find a way to provide an automatic redirect.
