### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#41]
It might be nice to have water.css published to npm with every release. Then, users can install it using `npm install water.css` and include it in their projects without referencing a CDN.

This would mean we would have to update the `package.json` version semantically with every release as well.

**Comment by kognise** [comment]
Great idea! I'm not that familiar with CSS frameworks being in an NPM package, so I'll research how that works.

On an unrelated note - thanks for all the help and great ideas you've contributed to Water.css. Do you mind if I make you a collaborator on the repo? This way you'll get cool access to more things (and also get nice badge next to your name iirc).

**Comment by kognise** [comment]
Ok, it seems CSS is usually just included like normal in the static markup at `node_modules/water.css/etc...`. Pretty simple.

**Comment by kognise** [comment]
So, the `water.css` package name on NPM is available, but here's something that could be better!

The package `water` has one version and was last published 7 years ago by a guy who doesn't contribute to basically anything. It seems to be some very specific code without any documentation that works with something else he's written, but it's obviously not used by anything anymore.

I think it'd be possible to contact NPM and get publish rights to this package - do you think if this is possible `water` is a better package name than `water.css`?

**Comment by Ryois** [comment]
> So, the `water.css` package name on NPM is available, but here's something that could be better!
> 
> The package `water` has one version and was last published 7 years ago by a guy who doesn't contribute to basically anything. It seems to be some very specific code without any documentation that works with something else he's written, but it's obviously not used by anything anymore.
> 
> I think it'd be possible to contact NPM and get publish rights to this package - do you think if this is possible `water` is a better package name than `water.css`?

Personally I prefer `water.css` as the package name. One is that your github repo's name is water.css, also to get publishing rights to the repo, it has to have not seen any downloads/ activity in the last few months.

**Comment by kylejrp** [comment]
Yep, I agree, I'm a bigger fan of `water.css`. 

> On an unrelated note - thanks for all the help and great ideas you've contributed to Water.css. Do you mind if I make you a collaborator on the repo? This way you'll get cool access to more things (and also get nice badge next to your name iirc).

Absolutely, thanks for working with me on all the contributions! I'd love to be a collaborator. Thanks! 🎉

**Comment by kognise** [comment]
@kylejrp Great, thanks! Yeah, I agree that `water.css` is probably better.

Also, [here](https://github.com/kognise/water.css/invitations)'s an invite link (if GitHub is working :).

**Comment by atilacamurca** [comment]
I suggest the use of <https://github.com/sindresorhus/np>, great tool for automate the publish process.

**Comment by kognise** [comment]
@atilacamurca Yeah, it is a great tool! Although, a lot of what that does we already do, it might not be optimal for this project. I've also had some issues with it in the past.

**Comment by chinanf-boy** [comment]
I think the simple  `package.json` template of css file is [the normalize.css - package.json](https://github.com/necolas/normalize.css/blob/master/package.json)

```json
{
  "name": "normalize.css",
  "version": "8.0.1",
  "description": "A modern alternative to CSS resets",
  "main": "normalize.css",
  "style": "normalize.css",
  "files": [
    "LICENSE.md",
    "normalize.css"
  ],
  "repository": "necolas/normalize.css",
  "license": "MIT",
  "bugs": "https://github.com/necolas/normalize.css/issues",
  "homepage": "https://necolas.github.io/normalize.css"
}
```

> May just replace normalize.css path with dist files

**Comment by kognise** [comment]
@chinanf-boy Thanks! I made some changes over in #42.

**Comment by FDiskas** [comment]
and.... it's dead :clock130:

**Comment by mdesantis** [comment]
<img src="https://media.giphy.com/media/XqpnXaeZPnupy/giphy.gif">

**Comment by kognise** [comment]
Moving the conversation to #187
