### ISSUE TITLE
Keep aspect ratio for images with height attribute

### ISSUE THREAD

**Issue by jgneff** [kognise/water.css#45]
If I add size attributes for the image on the demo page, as shown below, the kitten gets squeezed when its container width is smaller than the image width. The width is changed, but the height remains the same, so the image changes aspect ratios.

```html
<img src="https://placekitten.com/408/287" alt="Example kitten" width="408" height="287">
````

![squashed](https://user-images.githubusercontent.com/1413266/56070374-6bd43100-5d3c-11e9-8c83-f8a3346c259d.png)

But if I add `height: auto` to the `img` rule set in the *_base.scss* file, the image keeps its aspect ratio when resized.

```css
img {
  max-width: 100%;
  height: auto;
}
```

![better](https://user-images.githubusercontent.com/1413266/56070470-cc636e00-5d3c-11e9-97f2-f1630d7adb70.png)

I like to specify both *width* and *height* on any image, when known, so that the text on the page doesn't jump around as the images load. Can that line be added to the `img` rule set without causing other problems? Thank you.

**Comment by kylejrp** [comment]
This seems to be the exact same way that Bootstrap 4 handles their [responsive images](https://getbootstrap.com/docs/4.0/content/images/#responsive-images) - I think this is an easy pull request.

**Comment by jgneff** [comment]
Thanks for looking into it. I'll go ahead and submit the pull request.

It used to be considered bad form not to put size attributes on your images, but that seems to have gone out of fashion recently for a couple of reasons:

* They're not supported in general with [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/) nor part of [CommonMark](https://commonmark.org/help/).
* The size of the image loaded often depends on the size and pixel density of the receiving display.

The attributes are supported by GitHub Pages, though, because GitHub Pages uses Jekyll, which uses the Kramdown parser by default, which supports an Inline Attribute List (IAL) for putting the [*width* and *height* on images](https://kramdown.gettalong.org/syntax.html#images). So at least for GitHub Pages and other Jekyll sites, it's easy to let the browser know the size of the image ahead of time, when possible.

**Comment by jonaskuske** [comment]
@jgneff 
> I like to specify both width and height on any image, when known, so that the text on the page doesn't jump around as the images load.

Unfortunately, as soon as you put `height: auto` on them so they keep their aspect ratio, the page will start to jump again. 😕
`width` and `height` are treated as styling, not as information about the image itself, so overriding the image styling in CSS means you lose all the benefits of the fixed, unresponsive dimensions you specify.
The new `intrinsicsize` attribute is supposed to fix that, but until that is available everywhere, the hack using absolute positioning and `padding` to maintain aspect ratio in a responsive way is all we got I guess.

**Comment by jgneff** [comment]
> Unfortunately, as soon as you put `height: auto` on them so they keep their aspect ratio, the page will start to jump again, even if you specified `width` and `height` attributes.

Wow, you're right! Thanks for pointing that out. I just tested it by throttling to "GPRS" speed and checking "Disable cache" in the Network tab of Firefox Web Developer Tools. Read more about the problem at the [intrinsicsize Attribute Explainer](https://github.com/WICG/intrinsicsize-attribute).

So for now, there is no advantage in setting `height: auto`. I'll just have to make my pages load so quickly that the jumps are minimal. This issue can be closed.

By the way, [MDN still defines](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#Attributes) the *width* and *height* attributes as the intrinsic size of the image in pixels. It also states that setting an intrinsic size using *width* and *height* "is useful when you want to set the space taken up by an image to ensure the page layout is stable before it loads." But as soon as you add a `max-width: 100%` rule to your styles, the browser needs some other indicator for whether to adjust the height (whether to keep the aspect ratio). This appears to be the motivation behind `intrinsicsize`.

**Comment by jonaskuske** [comment]
@jgneff 

> But as soon as you add a max-width: 100% rule to your styles, the browser needs some other indicator

If you defined `width` and `height` and **only** set `max-width: 100%`, not `height: auto`, it still _"works"_ – the image will scale up to 100%, but keep the defined `height`. So it has a height right from the beginning which prevents layout shift, but the aspect ratio is broken.

That's why there still is an advantage to adding `height: auto` – images with set `width` and `height` will not have broken aspect ratios. Right now, if a user sets width and height on an image, we override the user-defined width, but keep the height. If we override image size, we need to override both axes – having images with set width and height look fine is not too much to expect from `water.css`, I think. 😅

**Comment by jgneff** [comment]
> That's why there still is an advantage to adding `height: auto` – images with set `width` and `height` will not have broken aspect ratios.

Right. I'll let others here decide whether to add the line.

For me, until something like `intrinsicsize` is supported, it doesn't seem worth it to add the image dimensions. I added them only to avoid page jumps while loading, but if you want the images to keep their aspect ratios, the jumps are back. Furthermore, for people using Markdown, dropping the Kramdown-specific dimensions has the advantage of making it more portable.

I also see that, on very slow connections, the page is displayed once without styling and then again (centered) after the CSS file loads, so some jumping is inevitable. I guess this battle was lost a long time ago. Thank you for your comments. I learned a lot.

> But the padding workaround is not _that_ bad either.

Thanks for taking the time to document the workaround. Tricks like that made me run from front-end Web development years ago. :smiley: I'm interested again because I learned of *classless* styles through *Water.css*. A simple classless style like *Water.css* is an inspiring design constraint.

**Comment by kylejrp** [comment]
We'd love to have someone contribute a pull request for this issue. This one is easy - the code is already written. We'd be looking for you to update `src/parts/_misc.scss`
```
img {
  max-width: 100%;
  height: auto;
}
```

**Comment by jonaskuske** [comment]
Will do, later today. :)

**Comment by kylejrp** [comment]
Awesome, thanks so much @jonaskuske!
