### ISSUE TITLE
Style of <select>

### ISSUE THREAD

**Issue by IL4Miy** [kognise/water.css#57]
I really love the library ❤️ but I think the `<select>` tag needs some adjustment.
It is hard to see a difference to a simple button.
<img width="540" alt="Bildschirmfoto 2019-04-20 um 16 47 05" src="https://user-images.githubusercontent.com/6071634/56458911-c6990880-638c-11e9-97b2-9e7861f48a9c.png">

Maybe an inline `svg` can be added to show that it is a `<select>`.
```
select {
  background: #949494
    url("data:image/svg+xml;utf8,<svg viewBox='0 0 140 140' width='24' height='24' xmlns='http://www.w3.org/2000/svg'><g><path d='m121.3,34.6c-1.6-1.6-4.2-1.6-5.8,0l-51,51.1-51.1-51.1c-1.6-1.6-4.2-1.6-5.8,0-1.6,1.6-1.6,4.2 0,5.8l53.9,53.9c0.8,0.8 1.8,1.2 2.9,1.2 1,0 2.1-0.4 2.9-1.2l53.9-53.9c1.7-1.6 1.7-4.2 0.1-5.8z'/></g></svg>")
    no-repeat;
  background-size: 12px;
  background-position: calc(100% - 15px) 57%;
  background-color: #efefef;
  padding-right: 35px;
}
```

Something like this looks good.
<img width="116" alt="Bildschirmfoto 2019-04-20 um 16 52 36" src="https://user-images.githubusercontent.com/6071634/56458905-b2550b80-638c-11e9-86bb-d9b8210c5d55.png">

Thank you for this cool lib :)

**Comment by IL4Miy** [comment]
Hmm, with this approach it looks weird when selecting the longest word from the options.

**Comment by kylejrp** [comment]
Would you be able to make a pull request for this? This looks great! 

@kognise might have some style recommendations in the pull request
