### ISSUE TITLE
<code> overlaps other lines

### ISSUE THREAD

**Issue by kimulaco** [kognise/water.css#59]
When `<code>` is adjacent to `<code>` in a different line, the background color will overlap.
This is also true for `<code>` in `<li>`.
I looking at Google Chrome.

![](https://user-images.githubusercontent.com/11986753/56460246-adb74400-63da-11e9-98b5-0810da3e0c41.png)

If you consider this markup, I think it is better to adjust `line-height`, `padding`, `margin`, etc...

**Comment by kognise** [comment]
I've noticed that and it's quite annoying - I'll get to fixing that write away!

**Comment by kimulaco** [comment]
Thanks!
In addition, I am sorry that I am different from the this issue.
When using `<code>` in `<table>`, the background color will overlap and it will not be visible in `<code>`.

![](https://user-images.githubusercontent.com/11986753/56465546-31544d80-643a-11e9-86c2-17c58b190511.png)

It may be safer to rethink the design of the code as a whole.

**Comment by kognise** [comment]
Or possibly rethink the design of the table.

**Comment by kylejrp** [comment]
> Or possibly rethink the design of the table.

Maybe light lines instead of dark? Or only show the background lines on hover?

**Comment by kognise** [comment]
Or possibly just a lighter highlight color - we could either create a new variable or `lighten`/`transparentize` the current color (I believe it's `$background-alt`)

**Comment by kimulaco** [comment]
I think that the same color as `$button-hover` may be used for `tr:nth-child(even)`.(we need to think about variable names)

**Comment by diomed** [comment]
what is going on with this?
is it fiXed?

**Comment by kylejrp** [comment]
@kognise Is this issue up for grabs?

**Comment by kimulaco** [comment]
If goal is fix, I can give a PR.

**Comment by kylejrp** [comment]
Go ahead @kimilaco!

**Comment by kimulaco** [comment]
@kylejrp @kognise 
OK. I will make PR while considering the design.
Please wait a moment.

**Comment by kimulaco** [comment]
@kognise @kylejrp This issue has been resolved.
There are no other tasks, so I close it.
Thank you!
