### ISSUE TITLE
Move light theme to it's own file

### ISSUE THREAD

**Issue by DanielBiegler** [kognise/water.css#6]
It's pretty hypocritical saying: 

> Water.css is a css framework that doesn't require any classes. You just include it in your <head> and forget about it, while it silently makes everything nicer.

But then for using the light theme I need to add a `.light`.

I think for clarity, size and ease of use it would be wise to split light and dark theme to their own files. When I want a light theme, why do I have to load all of the dark theme stylings? That's wasteful.

Splitting in respective files lends itself to creating more themes, for example a more red one, a blue one, a green one, grey, orange, etc.

**Comment by kognise** [comment]
How would this work development-wise? When fixing a style glitch it seems tedious to have to update the code in two files.

**Comment by DanielBiegler** [comment]
The themes only differ in color. Develop in one file and after it looks like you want it to look, copy paste it and replace colors. This would work even better with #7

**Comment by kylejrp** [comment]
I don't think copy and pasting is a great development workflow. It would make more sense to use SASS and some build tools here. The project source would then look something like:
- water.core.scss (containing styles that reference variables)
- water.light.scss (containing only the light theme variables)
- water.dark.scss (containing only the dark theme variables)

The build tools would then output something like:
- water-light.css
- water-dark.css

I think I could mock up an example this weekend if this is something @kognise thinks would adds value to the project.

**Comment by kylejrp** [comment]
For reference, this is how [Bootstrap's Theming](https://getbootstrap.com/docs/4.3/getting-started/theming/) works. You can take the core Bootstrap styles as is, or you can build your own version by creating a Sass file like this:
```
// Your variable overrides
$body-bg: #000;
$body-color: #111;

// Bootstrap and its default variables
@import "../node_modules/bootstrap/scss/bootstrap";
```

Then, your build tools would output your customized Bootstrap theme.

You wouldn't have to force Water.css end users to install any build tools - this is just more development work for contributors.

**Comment by kognise** [comment]
This sounds great - but brings up the question of SASS variables or CSS variables?

SASS variables: integrated with the build system, probably smaller bundle size, lets us do fancy things that may or may not be needed.

CSS variables: user theming doesn't need to set up a whole build system, accessible from the page if the user wants addon styles

**Comment by kylejrp** [comment]
I think CSS variables align more with the "just add water" goal, but you lose IE support. Sass would let us compile to something more compatible with more browsers, but you're right that it would complicate the build system.

Are we worried about theming being accessible from the page? I figure the target audience is people who don't want to touch CSS.

I think it's a decision on making it easy for the end users dropping CSS on their page vs. making it easy for contributors to add changes.

I think it's your call to make, @kognise! What do you think?

**Comment by kognise** [comment]
@kylejrp I'm thinking... probably Sass! I want to make good browser compatibility a goal, as well as small bundle sizes.

**Comment by kognise** [comment]
If we're gonna move the light theme to a different file, though, I wonder how dynamic switching in the demo will work...

**Comment by kylejrp** [comment]
I think we could just swap it with some javascript. Let me try to get a pull request up and running!

**Comment by DanielBiegler** [comment]
With Javascript you can dynamically switch stylesheets, that's no problem.
