### ISSUE TITLE
Switch Theme button doesn't work in IE11

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#61]
The switch theme button on the demo page doesn't work in IE11. I'm not seeing any bugs in the console, but this is definitely coming from the code in `script.js`.

It looks like it could just be the arrow function used on the first line. 
https://github.com/kognise/water.css/blob/f7ae16ada312eea8640f5b9a2f10ebc3a7bea5d1/script.js#L1

Caniuse mentions that it isn't supported in IE11:
https://caniuse.com/#feat=arrow-functions

To close this issue, we'd want to rewrite this function to be compatible with IE11 and test that the "switch theme" button works in IE11.

**Comment by pawptart** [comment]
It looks like you hit the nail on the head! The arrow function wasn't compatible with IE. I updated it to a regular anonymous function and have it working in IE & Chrome. 

I'll go ahead and submit a PR.
