### ISSUE TITLE
Update Theming Guide in README.md

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#83]
The source files for water.css were changed from SASS to just plain CSS using CSS variables. See the full details on #71. 

This made the theming guide in README.md out of date. It needs these minor updates: 
- The references to SASS should be removed.
- The variables should no longer be SASS variables. Instead of listing all our variables, we can just link to `src/variables-dark.css` or `src/variables-light.css`
- How to edit CSS variables in browser to test theming
- Basic Theming: How to override these CSS variables with your own stylesheet
- Advanced Theming: Information about setting up a custom build file in `src/builds/` should be added. There's a few types of builds that we should have descriptions for (see #71):
  - Normal (Like `dark.css`)
  - Standalone (Like `dark.standalone.css`)
  - Legacy (Like `dark-legacy.css`)
  - Legacy Standalone (Like `dark-legacy.standalone.css`)
- Policy around support for community themes from #26/#42

**Comment by kcclemo** [comment]
Is this issue still open?

**Comment by BeardedBry** [comment]
I'll try to make the changes listed here that I know how to do!

**Comment by kognise** [comment]
@kcclemo yeah, feel free to take a look
