### ISSUE TITLE
Demo page "switch theme" does not work.

### ISSUE THREAD

**Issue by kimulaco** [kognise/water.css#84]
@kognise @kylejrp @jonaskuske 
I think using CSS variables is a great idea!!(https://github.com/kognise/water.css/issues/70)
However, I found a problem on the [demo page](https://watercss.netlify.com/), though.

By use "prefers-color-scheme", it does not switch with "switch theme" on the demo page.
This is because the device's theme setting is prioritized.

So, in order to preview both "switch theme" and "prefers-color-scheme" on the demo page, I think it is necessary to take measures such as creating a dedicated demo page.(Page for loading "* .standalone.css".)

I am sorry if it has already been discussed somewhere or the correspondence is in progress.

**Comment by kylejrp** [comment]
Hah! Great catch. I don't think there was discussion about this before.

You're right that we'll probably have to use the standalone files to get this working.

**Comment by kimulaco** [comment]
In the future, I think personally it is better to use standalone files in demo page and use "prefers-color-scheme" in landing page.

For now, do change it to read standalone files now?
I can also give a PR.

**Comment by kylejrp** [comment]
Yeah, if you can make a pull request that switches to the standalone files, that would be great! Thanks a ton, @kimulaco.

Let's leave this open and discuss more after that merge. I personally like having the "most default" file on all pages where possible. Maybe some feature detection in the JavaScript?

**Comment by kimulaco** [comment]
@kylejrp I will try to adjust the switch by detect "prefers-color-scheme" with "window.matchMedia".
Please wait for a while before give the PR.

**Comment by jonaskuske** [comment]
Yes good catch, this needs to be taken care of with the new interactive version picker! (#27)
Then the version used on the demo site should always match the selected one, and there needs to be an explanation for the current display status. ("Light theme is selected, but your system is currently set to dark mode")

I think if we recommend the normal versions as default but always use standalone builds on the demo page, we pretty much "don't practice what we preach" and people will probably be confused why the demo page behaves differently than their own page.

**Comment by kimulaco** [comment]
I will adjusting to read the normal version by default.
Then, when the switching button is pressed, the switching theme is changed based on the loaded theme and the device theme.

I think that showing the status is a good idea!
I will try in this PR.

**Comment by kimulaco** [comment]
@kylejrp Since you can switch the theme, you can close this issue, but do you wait for the version picker?

**Comment by kylejrp** [comment]
I'll wait for #90 to automatically close the issue when it gets merged in.

**Comment by kognise** [comment]
This has been fixed in 2.0.
