### ISSUE TITLE
Create favicon

### ISSUE THREAD

**Issue by kimulaco** [kognise/water.css#86]
How about creating a favicon for use on demo pages etc?
As favicon is displayed on Google Search, setting a cool favicon will attract more users.
https://support.google.com/webmasters/answer/9290858?hl=en

**Comment by diomed** [comment]
yeah. maybe like a drop in the same style like logo is made

**Comment by kylejrp** [comment]
Great idea @kimulaco!

@kognise, do you have any of the resources you used to make the original logo?
