### ISSUE TITLE
tooltip styling

### ISSUE THREAD

**Issue by diomed** [kognise/water.css#95]
let's say we have this:

`<a href="#" data-toggle="tooltip" title="Hooray!">Hover over me</a>`

would be nice to implement something as this:

https://kazzkiq.github.io/balloon.css/

or something similar on your end

**Comment by jonaskuske** [comment]
I'd argue this is out of scope.
Water.css only styles native HTML elements so they match design expectations of the current century, it does not "invent" new elements.

The native "tooltip" of HTML is the `title` attribute.
Imo the only thing we could consider is automatically giving elements with a `title` attribute an underline and a different cursor so users can see that there's a tooltip, like I did here: https://deploy-preview-90--watercss.netlify.com/dist/docs/. But I don't know if this will bring unwanted side-effects with it.

(there also is `aria-role="tooltip"`, but it's for making custom tooltip implementations accessible and does not enforce some sort of standardized HTML structure we could target and style with CSS)

**Comment by kylejrp** [comment]
Agree with @jonaskuske, `data-` attributes are out of scope as they're used to extend HTML. `data-` attributes don't really have a semantic meaning in plain old HTML. We could consider styling the `title` attribute though.

I think that using balloon.css together with water.css makes the most sense if this is needed functionality. I don't see a reason why they wouldn't work together.
